name: On Pull Request

on:
  pull_request:

jobs:
  build_ant_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run build and tests
        run: |
          npm run build
          npm run test
  prepublish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: |
          echo "@abrahamosmonde:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          BUILD_VERSION=$(npm pkg get version 2> /dev/null | sed 's/"//g')
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          SEMVER_VERSION="$BUILD_VERSION-$SHORT_COMMIT"
          npm version $SEMVER_VERSION
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
