name: Build and Test

on:
  pull_request:

jobs:
  Build and Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run build and tests
        run: |
          npm run build
          npm run test
  Pre-publish Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: |
          BUILD_VERSION=$(npm pkg get version 2> /dev/null | sed 's/"//g')
          echo "::set-output name=build_version::$BUILD_VERSION"
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          echo "::set-output name=short_commit::$SHORT_COMMIT"
          npm publish --no-git-tag-version --new-version $(BUILD_VERSION)-$(SHORT_COMMIT)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
